- src/Arduino_ConnectionHandler.h
- src/Arduino_WiFiConnectionHandler.cpp
Internal ESP12 clock must be set in order to allow verification of certificate. This function just tasks the ESP framework with performing the NTP time sync, the time is not synched when this function returns. It may take a little while.
Necessary for https://github.com/arduino-libraries/ArduinoIoTCloud/pull/76
> ESP8266 - Internal clock needs to be set for certificate verification

- src/Arduino_ConnectionHandler.h
- src/Arduino_WiFiConnectionHandler.cpp
This PR extends the code to verify if any of the currently by the ESP8266 core supported boards are compiled with this library and includes the appopriate header files.
> Adding support for all ESP8266 based boards currently supported by ESP8266 core

- src/Arduino_NBConnectionHandler.cpp
This pull request fixes issues with the long constructor added in https://github.com/arduino-libraries/Arduino_ConnectionHandler/pull/12.
It appears PR #12 was merged without testing, this is very bad.
cc/ @AlbyIanna
> NBConnectionHandler: fix constructor chaining

- library.properties
The MKRNB library dependency was introduced with the MKR NB 1500 support (https://github.com/arduino-libraries/Arduino_ConnectionHandler/pull/7).
> Add MKRNB to dependencies list

- .github/workflows/compile-examples.yml
- .github/workflows/spell-check.yml
- Spell check all files.
- Compile all example sketches for the WiFi SAMD boards (Arduino currently has no established GitHub Actions mechanism to install the ESP8266 and ESP32 cores and the example isn't compatible with the non-WiFi boards the library supports).
Successful CI run: https://github.com/per1234/Arduino_ConnectionHandler/runs/383430744
> Use GitHub Actions for continuous integration tests

- src/Arduino_GSMConnectionHandler.cpp
- src/Arduino_GSMConnectionHandler.h
- src/Arduino_LoRaConnectionHandler.h
- src/Arduino_NBConnectionHandler.cpp
- src/Arduino_NBConnectionHandler.h
Removing while(1); to exit from the loop. Editing CHECK_INTERVAL_RETRYING value.
/CC @Rocketct
> Fix SIM not present bug

- .github/workflows/compile-examples.yml
- .github/workflows/install-python-wrapper.sh
The ESP8266 core for Arduino has Python 3 as a dependency. On Linux, instead of installing their own copy of Python 3, they assume it is already installed at `/usr/bin/python3` and only install a symlink to it. The Docker container used by the compile-examples action does not have Python 3 installed, so this required using a wrapper script as an alternate entrypoint when compiling for an ESP8266 board. The wrapper script installs Python 3 and then passes the arguments on to the standard entrypoint script.
> Run compile-examples CI action for ESP8266 board

- src/Arduino_ConnectionHandler.h
- src/Arduino_GSMConnectionHandler.h
- src/Arduino_LPWANConnectionHandler.h
- src/Arduino_LoRaConnectionHandler.h
- src/Arduino_NBConnectionHandler.h
- src/Arduino_TcpIpConnectionHandler.h
- src/Arduino_WiFiConnectionHandler.h
`ArduinoIoTCloud` uses only `check` therefore is no need to keep the function `update` around - it just adds to the confusion and provides no real benefit.
> Mark function 'update' as deprecated to be removed in a future release

- src/Arduino_ConnectionHandler.h
`netConnectionState` being initialized to `NetworkConnectionState::DISCONNECTED` caused the WiFiNINA library's [`SpiDrv::end()`](https://github.com/arduino-libraries/WiFiNINA/blob/13306fd60addb1a3027bfc5b04bbfe1fe0ed8c07/src/utility/spi_drv.cpp#L116-L124) to be called before [`SpiDrv::begin()`](https://github.com/arduino-libraries/WiFiNINA/blob/13306fd60addb1a3027bfc5b04bbfe1fe0ed8c07/src/utility/spi_drv.cpp#L66-L114). Since `SLAVESELECT` is [initialized to 10](https://github.com/arduino-libraries/WiFiNINA/blob/13306fd60addb1a3027bfc5b04bbfe1fe0ed8c07/src/utility/spi_drv.cpp#L52), and only [assigned `SPIWIFI_SS` in `SpiDrv::begin()`](https://github.com/arduino-libraries/WiFiNINA/blob/13306fd60addb1a3027bfc5b04bbfe1fe0ed8c07/src/utility/spi_drv.cpp#L73), this causes pin 10 to be [set to …
> Fix bug that sets pin 10 to INPUT on WiFi boards

- .github/workflows/compile-examples.yml
- .github/workflows/install-python-wrapper.sh
Previously, this script was needed to install the ESP8266 platform's Python dependency during the CI run. Since then, the `arduino/actions/libraries/compile-examples` action has been modified to install Python, so that is no longer necessary.
> Remove wrapper script previously required for ESP8266 CI build

- .github/workflows/compile-examples.yml
- .github/workflows/report-size-deltas.yml
On every push to a pull request, the change in memory usage of `examples/ConnectionHandlerDemo` between the PR's head and base branch for each of the boards in the board matrix will be:
- Shown in the log
- Saved to a workflow artifact (can be seen [here](https://github.com/arduino-libraries/Arduino_ConnectionHandler/pull/31/checks?check_run_id=595712256))
- Commented to the PR's thread as a table (after a delay of ~7 minutes max.)
---
Demo: https://github.com/per1234/Arduino_ConnectionHandler/pull/2#issuecomment-615291325
> Report memory usage change caused by PRs

- .github/workflows/compile-examples.yml
Running the Compile Examples GitHub Actions workflow is only necessary when files under `examples/`, `src/`, or the workflow configuration itself are modified. For any other changes, the workflow run only slows down the CI results and causes unnecessary comments from the `report-size-deltas` workflow.
Reference:
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
> Only run Compile Examples workflow when relevant files are modified

- src/Arduino_GSMConnectionHandler.cpp
Calling attachGPRS multiple times is not handled well by the MRK GSM/MKR GSM stack. But this is exactly what happens when the first call to ping fails. Consequently the attachGPRS part has been moved one state up so it will be only called once.
> Bugfix: Don't break MKRGSM stack when ping fails.

- .github/workflows/compile-examples.yml
The library examples will be compiled for Portenta H7 (M7 core) and Portenta H7 (M4 core) boards, using the Arduino mbed OS-enabled boards platform from the tip of its repository's default branch.
Fixes https://github.com/arduino-libraries/Arduino_ConnectionHandler/issues/38
> Add Portenta H7 boards to matrix jobs in Compile Examples CI workflow

- .github/workflows/compile-examples.yml
Recent changes to the Arduino Mbed OS Boards platform core's handling of the `arduino/ArduinoCore-API` repository resulted in the need to adjus how the "Compile Examples" CI workflow installs it for those boards.
---
The symlink for ArduinoCore-API in the Mbed OS Boards core library has been removed (https://github.com/arduino/ArduinoCore-mbed/commit/ca397e88926c16ccfd7531f842a2d8f0971dcffc). This resulted in the step of the "Compile Examples" CI workflow that removes the now non-existent symlink to fail.
---
Previously, the `namespace_arduino` branch of ArduinoCore-API was used in the core library of the development version of
the Mbed OS Boards platform used in the "Compile Examples" CI workflow. The default branch of ArduinoCore-API is now the
latest and greatest version, so the …
> Update CI workflow to correctly install ArduinoCore-API in arduino:mbed core

- examples/ConnectionHandlerDemo/ConnectionHandlerDemo.ino
- src/Arduino_ConnectionHandler.h
- src/Arduino_WiFiConnectionHandler.cpp
This PR adds ConnectionHandler support for ESP32-based boards and fixes the demo example which was still calling `setDebugLevel()` although that was not enabled for MegaAVR
> ESP32 support + example fix (AVR DebugUtils removal)

- .github/workflows/compile-examples.yml
- src/Arduino_ConnectionHandler.cpp
ESP32 support has been added to the library, so the examples compilation smoke test should be done for this architecture
as well.
Fixes https://github.com/arduino-libraries/Arduino_ConnectionHandler/issues/48
> Add ESP32 board to "Compile Examples" CI workflow

- .github/workflows/compile-examples.yml
Previously, the most recent release of the ESP8266 boards platform (currently 2.7.4) was used in the "Compile Examples"
CI workflow. Arduino Create uses 2.5.0, so it's best to use that version for testing as well.
> Pin esp8266:esp8266 platform version to 2.5.0 in CI builds

- library.properties
Note: We are already using it on Portenta H7.
> Adding 'mbed' as supported library to Arduino_ConnectionHandler library

- src/Arduino_GSMConnectionHandler.cpp
- src/Arduino_NBConnectionHandler.cpp
modems - this takes a bit of time.
> Feed watchdog a bit more often when initializing MKR GSM 1400/NB 1500

- .github/workflows/compile-examples.yml
The API of the `arduino/compile-sketches` GitHub Actions action used to compile the library's example sketches in the "Compile Examples" CI workflow has evolved over time. Although measures were taken to provide backwards compatibility for the old API, it turns out that the GitHub Actions behavior of creating environment variables for arbitrary input names relied upon for still recognizing the old inputs is not consistent across action types. It works fine for the Docker container action type originally used by `arduino/compile-sketches`, but not for the new "Composite Run Steps" action type we switched to (https://github.com/arduino/compile-sketches/pull/14).
This change resulted in sketch data deltas no longer being generated due to the workflow's use of the unsupported input name …
> Use modern API of `arduino/compile-sketches` action

- src/Arduino_LoRaConnectionHandler.cpp
- src/Arduino_LoRaConnectionHandler.h
Enable setting sub band frequency into LoraWan Connection handler constructor.
Expose LoraWan modem getters.
> Add channel mask to LoraWan constructor and expose LoraWan modem getters

- .github/workflows/compile-examples.yml
- src/Arduino_ConnectionHandler.h
As of now, even if the build is fine, the wifi module is not working on the M4.
Goal of this pr is to remove the portenta M4 core from the build to keep the code clean.
If and when the wifi module will work on the M4 i will re-add the core.
> ARDUINO_PORTENTA_H7_M4: Remove from supported build options

- src/Arduino_ConnectionHandler.h
- src/Arduino_WiFiConnectionHandler.cpp
Just a minor change to keep things tidy. Nothing has changed in terms of boards supported.
> Use generic defines ARDUINO_ARCH_ESP8266 and ARDUINO_ARCH_ESP32

- src/Arduino_LoRaConnectionHandler.cpp
Issue: user reported problems on multiple boards not connecting to the network and to ArduinoIoTCloud. The boards are printing the following message on the serial monitor:
`Something went wrong; are you indoor? Move near a window, then reset and retry.`
and after they start looping without doing nothing.
Proposed solution: This patch adds automatic retries if `joinOTAA(...)` fails, this is very similar to what we are doing in the `CONNECTING` state of `WiFiConnectionHandler` calling` WiFi.begin(...)` until board gets connected.
> LoRa: add retries if joinOTAA(...) fails

- src/Arduino_ConnectionHandler.h
- src/Arduino_WiFiConnectionHandler.cpp
Issue 1: i've got 2 ESP8266 boards and they are not able to connect to my WiFi with the current implementation: it looks like this delay is not enough to get the board connected.
```
WiFi.begin(_ssid, _pass);
delay(1000);
```
Solution: delay until the board is connected with a maximum timeout of 3s
```
#if defined(ARDUINO_ARCH_ESP8266)
/* Wait connection otherwise board won't connect */
unsigned long start = millis();
while((WiFi.status() != WL_CONNECTED) && (millis() - start) < ESP_WIFI_CONNECTION_TIMEOUT) {
delay(100);
}
#endif
```
Issue 2: both my ESP8266 and ESP32 board are not alway reconneting to WiFi if connection drops (power off WiFi from the router)
Solution: moving `WiFi.begin(_ssid, _pass);` in `CONNECTING` status with a proper retry delay solves the issue for both boards
> ESP: WiFi: Fix (re)connection 

- src/Arduino_NBConnectionHandler.cpp
NB_NetworkStatus_t::ERROR has been renamed to NB_NetworkStatus_t::NB_ERROR in MKRNB library release 1.6.0
> Fix build after MKRNB library release 1.6.0

- .github/workflows/compile-examples.yml
- examples/ConnectionHandlerDemo/ConnectionHandlerDemo.ino
- keywords.txt
- src/Arduino_CatM1ConnectionHandler.cpp
- src/Arduino_CatM1ConnectionHandler.h
- src/Arduino_ConnectionHandler.h
This PR adds support for the `Portenta CAT.M1/NB IoT GNSS Shield`. The shield provides `CatM1` and `NB-IoT` connectivity in a very similar way the `SARA-R410M-02B` module of the `MKRNB1500` does.
Even if it was possible to reuse the already present `NBConnectionHandler` i preferred to create a new one to avoid messing up the `NBConnectionHandler` with too much `#ifdef`
> Add CatM1ConnectionHandler to support Portenta CAT.M1/NB IoT GNSS Shield

- src/Arduino_EthernetConnectionHandler.cpp
- src/Arduino_EthernetConnectionHandler.h
This PR adds support for specifying custom timeouts on Ethernet connections.
Combined with the ArduinoIoTCloud library, this PR allows writing sketches that don't block for 15s in the `loop()` if the Ethernet cable is not connected or there is no link-layer connectivity.
To be used as:
```C++
EthernetConnectionHandler ArduinoIoTPreferredConnection(IP, DNS, GATEWAY, NETMASK, 1000);
```
```C++
auto connStatus = ArduinoIoTPreferredConnection.check();
if (connStatus == NetworkConnectionState::CONNECTED)
ArduinoCloud.update();
```
> Add support for custom Ethernet timeouts

- examples/GenericConnectionHandlerDemo/GenericConnectionHandlerDemo.ino
- examples/GenericConnectionHandlerDemo/arduino_secrets.h
- src/CatM1ConnectionHandler.cpp
- src/CatM1ConnectionHandler.h
- src/CellularConnectionHandler.cpp
- src/CellularConnectionHandler.h
- src/ConnectionHandlerDefinitions.h
- src/ConnectionHandlerInterface.cpp
- src/ConnectionHandlerInterface.h
- src/EthernetConnectionHandler.cpp
- src/EthernetConnectionHandler.h
- src/GSMConnectionHandler.cpp
- src/GSMConnectionHandler.h
- src/GenericConnectionHandler.cpp
- src/GenericConnectionHandler.h
- src/LoRaConnectionHandler.cpp
- src/LoRaConnectionHandler.h
- src/NBConnectionHandler.cpp
- src/NBConnectionHandler.h
- src/WiFiConnectionHandler.cpp
- src/WiFiConnectionHandler.h
- src/connectionHandlerModels/settings.h
- src/connectionHandlerModels/settings_default.h
The objective of this PR is to make the implementation of the various connection handler more generic.
with this change it was possible to create a GenericConnection handler that is able to be instantiated in conditions where the kind of connection has to be decided at runtime.
Testing connection handler
mbed core       f7ff4114bc0d89f23b45423e049f5bc17114dcbc
renesas core    84d44b8f42bb657d66aa8fdda66f789f294dfddd
samd core       993398cb7a23a4e0f821a73501ae98053773165b
Board Name                            | Demo      | PHY
----                                  | ----      | ----
arduino:esp32:nano_nora               | OK        | WiFI
arduino:mbed_giga:giga                | OK        | WiFI
arduino:mbed_nano:nanorp2040connect   | OK        | WiFI
arduino:mbed_nicla:nicla_vision …
> GenericConnectionhandler redesign of internal structures

- .github/workflows/compile-examples.yml
- examples/CheckInternetAvailabilityDemo/CheckInternetAvailabilityDemo.ino
- examples/CheckInternetAvailabilityDemo/arduino_secrets.h
- src/CatM1ConnectionHandler.cpp
- src/CellularConnectionHandler.cpp
- src/ConnectionHandlerDefinitions.h
- src/ConnectionHandlerInterface.cpp
- src/ConnectionHandlerInterface.h
- src/EthernetConnectionHandler.cpp
- src/GSMConnectionHandler.cpp
- src/GenericConnectionHandler.cpp
- src/WiFiConnectionHandler.cpp
This PR introduce a step of validation that the board has access to internet before giving the "Connected" result.
The PR requires this [PR ](https://github.com/arduino-libraries/MKRNB/pull/129) on MKRNB lib
> Check internet availability

- examples/ConnectionHandlerTimeoutTable/ConnectionHandlerTimeoutTable.ino
- examples/ConnectionHandlerTimeoutTable/arduino_secrets.h
- src/CatM1ConnectionHandler.cpp
- src/CellularConnectionHandler.cpp
- src/ConnectionHandlerDefinitions.h
- src/ConnectionHandlerInterface.cpp
- src/ConnectionHandlerInterface.h
- src/EthernetConnectionHandler.cpp
- src/GSMConnectionHandler.cpp
- src/LoRaConnectionHandler.cpp
- src/NotecardConnectionHandler.cpp
- src/WiFiConnectionHandler.cpp
changing the approach from defining a static array CHECK_INTERVAL_TABLE we can allow the user to change timeout values at runtime depending on his needs.
This addresses https://github.com/arduino-libraries/Arduino_ConnectionHandler/issues/139
> Defined TimeoutTable for the user to customize timeouts
